name: Waka

on:
  push:
    branches: 'master'
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '10 10 * * *'

jobs:
  update-readme:
    name: Update Readme With Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"
          SHOW_COMMIT: "True"
